### ISSUE TITLE
OpenJDK 11 Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Date

### ISSUE THREAD

**Issue by kennethgillen** [blangel/wrk#14]
Freshly installed OpenJDK 11 and `wrk-trello` via Homebrew:

```
computer:~ vmware$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```
Trying to start `wrk` leads to:
```
computer:~ user$ wrk
Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Date
        at org.codehaus.jackson.map.deser.std.StdDeserializer$SqlDateDeserializer.<init>(StdDeserializer.java:1079)
        at org.codehaus.jackson.map.deser.StdDeserializers.<init>(StdDeserializers.java:76)
        at org.codehaus.jackson.map.deser.StdDeserializers.constructAll(StdDeserializers.java:103)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.<clinit>(BasicDeserializerFactory.java:46)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.<init>(StdDeserializerProvider.java:81)
        at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:398)
        at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:358)
        at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:328)
        at net.ocheyedan.wrk.Json.<clinit>(Json.java:13)
        at net.ocheyedan.wrk.Config.init(Config.java:79)
        at net.ocheyedan.wrk.Wrk.main(Wrk.java:18)
```

**Comment by blangel** [comment]
@kennethgillen right.  Java since 8 has new restrictions on reflection access and exporting of module types.  I'll look into this in the coming days.  I honestly haven't been maintaining this project but will try to devout some time to it.

**Comment by kennethgillen** [comment]
No worries.

FYI it works fine with a fresh `brew cask install java8` - 

```
computer:~ user$ java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

**Comment by israelbuitron** [comment]
I still having this error.

I have installed java 11 by running `brew install java11`.
I have verified its version
```java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```

Finally, this error still appearing:

```$ wrk
Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Date
	at org.codehaus.jackson.map.deser.std.StdDeserializer$SqlDateDeserializer.<init>(StdDeserializer.java:1079)
	at org.codehaus.jackson.map.deser.StdDeserializers.<init>(StdDeserializers.java:76)
	at org.codehaus.jackson.map.deser.StdDeserializers.constructAll(StdDeserializers.java:103)
	at org.codehaus.jackson.map.deser.BasicDeserializerFactory.<clinit>(BasicDeserializerFactory.java:46)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider.<init>(StdDeserializerProvider.java:81)
	at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:398)
	at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:358)
	at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:328)
	at net.ocheyedan.wrk.Json.<clinit>(Json.java:13)
	at net.ocheyedan.wrk.Config.init(Config.java:79)
	at net.ocheyedan.wrk.Wrk.main(Wrk.java:18)
$ wrk orgs
Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Date
	at org.codehaus.jackson.map.deser.std.StdDeserializer$SqlDateDeserializer.<init>(StdDeserializer.java:1079)
	at org.codehaus.jackson.map.deser.StdDeserializers.<init>(StdDeserializers.java:76)
	at org.codehaus.jackson.map.deser.StdDeserializers.constructAll(StdDeserializers.java:103)
	at org.codehaus.jackson.map.deser.BasicDeserializerFactory.<clinit>(BasicDeserializerFactory.java:46)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider.<init>(StdDeserializerProvider.java:81)
	at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:398)
	at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:358)
	at org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:328)
	at net.ocheyedan.wrk.Json.<clinit>(Json.java:13)
	at net.ocheyedan.wrk.Config.init(Config.java:79)
	at net.ocheyedan.wrk.Wrk.main(Wrk.java:18)
```

**Comment by carlosonunez** [comment]
unfortunately this makes `wrk` unusable on M1 Macs, as no ARM64 version of Java8 exists.
